# Generated by Django 4.2.11 on 2024-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrivibe', '0002_exercises_orders_ordersitems_products_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
