# Generated by Django 4.2.11 on 2024-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrivibe', '0003_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
