# Generated by Django 4.2.11 on 2024-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrivibe', '0004_alter_products_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='calories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
