# Generated by Django 4.2.11 on 2024-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrivibe', '0005_products_calories_products_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='difficulty',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='structure',
        ),
    ]
