# Generated by Django 4.2.11 on 2024-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrivibe', '0007_rename_video_url_recipes_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
